import{A as f,i as y,a as k}from"./assets/vendor-D1rhCP_o.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))o(i);new MutationObserver(i=>{for(const t of i)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(i){const t={};return i.integrity&&(t.integrity=i.integrity),i.referrerPolicy&&(t.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?t.credentials="include":i.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(i){if(i.ep)return;i.ep=!0;const t=n(i);fetch(i.href,t)}})();new f(".accordion-container",{openOnInit:[0],collapse:!1,beforeOpen:e=>{e.classList.add("open")},beforeClose:e=>{e.classList.remove("open")}});document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".projects-list"),s=document.querySelector(".load-more-btn"),n=[{img1x:"../img/projects/power-1x-desk.jpg",img2x:"../img/projects/power-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"power pulse webservice",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/mimino-1x-desk.jpg",img2x:"../img/projects/mimino-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"mimino website",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/vyshyvanka-1x-desk.jpg",img2x:"../img/projects/vyshyvanka-2x-dessk.jpg",tech:"React, JavaScript, Node.js, Git",title:"vyshyvanka vibes Landing Page",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/chego-1x-desk.jpg",img2x:"../img/projects/chego-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"chego jewelry website",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/energy-1x-desk.jpg",img2x:"../img/projects/energy-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"energy flow webservice",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/fruitbox-1x-desk.jpg",img2x:"../img/projects/fruitbox-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"fruitbox online store",link:"https://github.com/aleks-zhiv/CodeNova.git"},{img1x:"../img/projects/starlight-1x-desk.jpg",img2x:"../img/projects/starlight-2x-desk.jpg",tech:"React, JavaScript, Node.js, Git",title:"starlight studio landing page",link:"https://github.com/aleks-zhiv/CodeNova.git"}];let o=0;s.addEventListener("click",()=>{n.slice(o,o+3).forEach(t=>{const c=document.createElement("li");c.classList.add("project-item"),c.innerHTML=`
       <picture class="project-picture">
    <source srcset="${t.img2x} 2x, ${t.img1x} 1x">
    <img src="${t.img1x}" alt="${t.title}" class="project-image">
  </picture>

        <div class="project-info">
          <p class="project-tech">${t.tech}</p>
          <div class="project-header">
            <h3 class="title">${t.title}</h3>
<div class="visit-button-wrapper">
    <a href="${t.link}" target="_blank" class="visit-button">
     Visit
     <svg class="visit-icon" width="24" height="24">
          <use href="./img/icons.svg#icon-visit"></use>
    </svg>
    </a>
</div>
          </div>
        </div>
      `,e.appendChild(c)}),o+=3,o>=n.length&&(s.style.display="none")})});const p=document.querySelector(".mobile-menu"),L=document.querySelector(".open-mob-menu-btn"),j=document.querySelector(".mob-menu-close-btn"),b=document.querySelectorAll(".mob-menu-nav-list-link"),d=document.body,u=document.querySelector("#theme-switcher");L.addEventListener("click",x);j.addEventListener("click",h);localStorage.getItem("theme")==="dark"&&(d.classList.add("dark-theme"),u.checked=!0);u.addEventListener("change",S);b.forEach(e=>{e.addEventListener("click",h)});function x(){p.classList.add("is-open")}function h(){p.classList.remove("is-open")}function S(){u.checked?(d.classList.add("dark-theme"),localStorage.setItem("theme","dark")):(d.classList.remove("dark-theme"),localStorage.setItem("theme","light"))}function E(e,s){return k.post("https://portfolio-js.b.goit.study/api/requests",{email:e,comment:s})}const v=document.querySelector(".work-together-form"),w=document.querySelector(".modal-close"),r=document.querySelector(".backdrop"),a=document.getElementById("email"),m=document.querySelector(".success-filled"),l=document.querySelector(".invalid-email");v.addEventListener("submit",M);a.addEventListener("input",N);w.addEventListener("click",g);r.addEventListener("click",C);document.addEventListener("keydown",O);async function M(e){e.preventDefault();const s=e.target.email.value.trim(),n=e.target.message.value.trim();m.classList.add("visually-hidden");try{const o=await E(s,n);o.status===201&&(v.reset(),q(o.data.title,o.data.message))}catch{z()}}function N(){a.validity.valid?(l.classList.add("visually-hidden"),a.classList.remove("no-valid"),m.classList.remove("visually-hidden")):(a.classList.add("no-valid"),l.classList.remove("visually-hidden"),m.classList.add("visually-hidden"),a.value.trim()===""&&l.classList.add("visually-hidden"))}function q(e,s){r.classList.remove("visually-hidden"),document.body.classList.add("no-scroll"),document.querySelector(".modal-title").innerHTML=e,document.querySelector(".modal-text").innerHTML=s}function g(){r.classList.add("visually-hidden"),document.body.classList.remove("no-scroll")}function C(e){e.target.classList.contains("backdrop")&&g()}function O(e){e.key==="Escape"&&!r.classList.contains("visually-hidden")&&g()}function z(){y.show({title:"An error occurred!",message:"Correct the entered data and send again",position:"center",maxWidth:"300px"})}
//# sourceMappingURL=index.js.map
